// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Services.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class MyModel
    {
        /// <summary>
        /// Initializes a new instance of the MyModel class.
        /// </summary>
        public MyModel() { }

        /// <summary>
        /// Initializes a new instance of the MyModel class.
        /// </summary>
        public MyModel(string id = default(string), int? score = default(int?), string name = default(string), IList<string> roles = default(IList<string>))
        {
            Id = id;
            Score = score;
            Name = name;
            Roles = roles;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "score")]
        public int? Score { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "roles")]
        public IList<string> Roles { get; set; }

    }
}
